<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$_category  = $block->getCurrentCategory();
$_ParentCategory = $_category->getParentCategory();
$_GrandParentCategory = $_ParentCategory->getParentCategory();
$_imgHtml   = '<div class="category-image">';
if ($_ParentCategory->getLevel() == 4) {
    if ($_imgUrl_grand = $_GrandParentCategory->getImage()) {
        $_imgHtml .= '<a href="'.$_GrandParentCategory->getUrl().'"><img src="'
            . $block->escapeUrl($_imgUrl_grand)
            . '" alt="'
            . $block->escapeHtmlAttr($_GrandParentCategory->getName())
            . '" title="'
            . $block->escapeHtmlAttr($_GrandParentCategory->getName())
            . '" class="image" /></a>';
    }
}
if ($_imgUrl_parent = $block->getImage()->getUrl($_ParentCategory)) {
    $_imgHtml .= '<a href="'.$_ParentCategory->getUrl().'"><img src="'
        . $block->escapeUrl($_imgUrl_parent)
        . '" alt="'
        . $block->escapeHtmlAttr($_ParentCategory->getName())
        . '" title="'
        . $block->escapeHtmlAttr($_ParentCategory->getName())
        . '" class="image" /></a></div>';
    $_imgHtml = $block->getOutput()->categoryAttribute($_ParentCategory, $_imgHtml, 'image');
    /* @noEscape */ echo $_imgHtml;
}
?>
