<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.IncorrectExact
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput
?>
<?php
$_category  = $block->getCurrentCategory();
$_imgHtml   = '<div class="category-image" major="'.$_category->getLevel().'">';
if ($_category->getLevel() == 4) {
    $objectManager_parent = \Magento\Framework\App\ObjectManager::getInstance();
    $category_parent = $objectManager_parent->get('Magento\Framework\Registry')->registry('current_category');//get current category
    if ($_imgUrl_parent = $category_parent->getParentCategory()->getImage()) {
        $_imgHtml .= '<a href="'.$category_parent->getParentCategory()->getUrl().'"><img src="'
            . $block->escapeUrl($_imgUrl_parent)
            . '" alt="'
            . $block->escapeHtmlAttr($category_parent->getParentCategory()->getName())
            . '" title="'
            . $block->escapeHtmlAttr($category_parent->getParentCategory()->getName())
            . '" class="image" /></a>';
    }
}
if ($_imgUrl = $block->getImage()->getUrl($_category)) {
    $_imgHtml .= '<img src="'
        . $block->escapeUrl($_imgUrl)
        . '" alt="'
        . $block->escapeHtmlAttr($_category->getName())
        . '" title="'
        . $block->escapeHtmlAttr($_category->getName())
        . '" class="image" /></div>';
    $_imgHtml = $block->getOutput()->categoryAttribute($_category, $_imgHtml, 'image');
    /* @noEscape */ echo $_imgHtml;
}
?>
