<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category


$category =  $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
$_ParentCategory = $category->getParentCategory();
$_GrandParentCategory = $_ParentCategory->getParentCategory();


?>




<style>
    .slick-dots li button {background:darkcyan;}
    #layered-filter-block{display:none;}
    .modal-popup .modal-inner-wrap{
        width:80%;
        margin:2rem auto;
    }
    .a-category-quicview-iframe{width:100%;}
    .sections.nav-sections,
    .page-layout-1column .filter.block,
    .modal-header,.modal-footer,.copyright,.page-title-wrapper{display:none;}
    .modal-popup .modal-content{padding:0px !important;}
    .product-quickview {
        overflow: hidden;
        padding-top: 56.25%;
        position: relative;
    }

    .product-quickview iframe {
        border: 0;
        height: 100%;
        left: 0;
        position: absolute;
        top: 0;
        width: 100%;
    }
    .category-image img{margin:auto;}
    #maincontent{padding:0px;margin:0px;max-width:none;}
    .maincontent{height:100%;}
    .category-view{height:100%;width:25%;float:left;background:#000;}
    .category-view img {width: 75%;margin: auto;background: #fff;padding: 3%;border: 1px #000 solid;border-radius: 5px;margin-top:5%;}
    .columns{width:75%;float:left;background: cornsilk;}
    .columns .column.main{background: cornsilk;margin: auto;padding: 1%;width:95%;}
    body{background:darkcyan;}
    button.slick-prev.slick-arrow{box-shadow:none;}
    .block-promo{display: block;border: solid 1px #fff;padding: 3%;background: #000;border-radius: 15px;color: #fff;width:85%;}
</style>
<div class="theslick">
    <?php
    $subcats = $_GrandParentCategory->getChildrenCategories();
    $_four_count = 0;
    foreach ($subcats as $subcat) {
        if ($subcat->getIsActive()) {
            $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
            $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
            $subcaturl = $subcat->getUrl();
            $_imgHtml = '';
            if ($_imgUrl = $_category->getImageUrl()) {
                $_four_count = $_four_count +1;
                $_show_count = array();
                $_imgHtml = '<img style="width: 100%;" src="' . $_imgUrl . '" />';
                $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
                $_all_data = $_category->getProductCollection()->addAttributeToSelect('*');
                foreach($_all_data as $_a_show){
                    $_show_count[]= $_a_show->getIdentifier();
                }
                echo '<div style="text-align:center;"><a href="' . $subcaturl . '
				" class="block-promo" title="' . $subcat->getName() . '">'.$subcat->getName() .$_imgHtml. count($subcat->getProductCollection()->addAttributeToSelect('entity_id'))  . ' recordings from '. count(array_unique($_show_count)).' shows</a></div>';
            }
        }
    } ?>
</div>






<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        jQuery(document).ready(function () {
            jQuery(".theslick").slick({
                dots: true,
                infinite: true,
                speed: 300,
                slidesToShow: 4,
                slidesToScroll: 1
            });
        });
    });
</script>





<table width="100%">
    <tr>
        <td width="20%" style="padding-right:0px;">



            <?php
            $displaysubcats = $_ParentCategory->getChildrenCategories();
            $track_count = 0;
            foreach ($displaysubcats as $_display_me) {
                $track_count += 1;
                $_style = '';
                if($category->getName() == $_display_me->getName()){
                    $_style = ' style="font-weight:bold;background:#fff;padding:3px 0px 3px 2px;color:#000;"';
                }
                //echo '<div style="font-size:105%">#'.$track_count.' <a href="'.$_display_me->getUrl().'">'.$_display_me->getName().'  <sup>'.$_display_me->getProductCount().' live versions</sup></a></div>';
                echo '<div'.$_style.'><a'.$_style.' href="'.$_display_me->getUrl().'">'.$_display_me->getName().'<sup>'.$_display_me->getProductCount().'</a></div>';
            }
            ?>



        </td>
        <td width="80%" style="background:#fff;font-size:80%">



            <?php if (!$_productCollection->count()): ?>
                <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
            <?php else: ?>
            <?php echo $block->getToolbarHtml() ?>
            <?= $block->getAdditionalHtml() ?>
            <?php
            if ($block->getMode() == 'grid') {
                $viewMode = 'grid';
                $imageDisplayArea = 'category_page_grid';
                $showDescription = false;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            } else {
                $viewMode = 'list';
                $imageDisplayArea = 'category_page_list';
                $showDescription = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
            }
            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
            ?>
                <style>
                    .plp-list-wrapper {
                        display: grid;
                        grid-template-columns: 15% 10% 8% 37% 15% 10%;
                        grid-gap: 0px;
                        border-bottom:1px solid #ccc;
                    }
                    .plp-list-box {
                        padding: 0%;
                    }
                    .plp-list-box-drop1-1{
                        grid-column: 1 ;
                        grid-row: 1/3;
                    }
                    .plp-list-box-drop1-2{
                        grid-column: 2 ;
                        grid-row: 1/3;
                    }
                    .plp-list-box-run3{
                        grid-column: 3/8;
                        grid-row: 2;
                        font-size: 89%;
                    }
                    .action.primary{
                        padding: 5px;
                        background: #fff;
                        color: #000;
                        border: none;
                    }
                </style>
                <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <div data-role="content">
                        <ol style="padding-left:7px;">
                            <li class="plp-list-wrapper">
                                <div class="plp-list-box"><strong></strong></div>
                                <div class="plp-list-box"><strong>Date</strong></div>
                                <div class="plp-list-box"><strong>Length</strong></div>
                                <div class="plp-list-box"><strong>Venue</strong></div>
                                <!--div class="plp-list-box"><strong>Source</strong></div-->
                                <div class="plp-list-box"><strong>Taper</strong></div>
                                <div class="plp-list-box"><strong>Transferrer</strong></div>
                            </li>

                            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                            <?php
                            $_fix_me_artist = 1;
                            $_artist_holder = '';
                            $on_artist = '';
                            $_fix_me_album = 1;
                            $_album_holder = '';
                            $on_album = '';
                            $_fix_me_track = 1;
                            $_track_holder = '';
                            $on_track = '';
                            foreach ($_productCollection as $_product):
                                $on_artist = $_product->getAttributeText('artist');
                                $on_album = substr($_product->getAttributeText('album_track'), stripos($_product->getAttributeText('album_track'),'_')+1);
                                $on_album = substr($on_album, 0, strrpos($on_album,'_'));
                                $on_track = substr($_product->getAttributeText('album_track'), strrpos($_product->getAttributeText('album_track'),'_')+1);
                                ?>


                                <li class="plp-list-wrapper">
                                    <?php
                                    $productImage = $block->getImage($_product, $imageDisplayArea);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php // Product Image ?>
                                    <!--a class="plp-list-box plp-list-box-drop1-1" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                </a-->
                                    <div class="plp-list-box">
                                        <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                        ?>


                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Playlist')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Playlist') ?></span>
                                                    </button>
                                                </form>
                                            <?php endif; ?>
                                        </div>



                                    </div>
                                    <div class="plp-list-box"><?php echo date('d.m.Y',strtotime($_product->getShowDate())); ?></div>
                                    <div class="plp-list-box"><?php echo ltrim(gmdate("i:s",$_product->getLength()), 0);; ?></div>
                                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_venue') ?></div>
                                    <!--div class="plp-list-box">Archive.org</div-->
                                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_taper') ?></div>
                                    <div class="plp-list-box"><?php echo $_product->getAttributeText('show_transferer') ?></div>
                                </li>
                            <?php endforeach; ?>
                        </ol>
                    </div>
                </div>
                </div>
            <?php echo $block->getToolbarHtml()  ?>
            <?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
                    {
                        "[data-role=tocart-form], .form.map.checkout": {
                            "catalogAddToCart": {
                                "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                            }
                        }
                    }
                    </script>
            <?php endif; ?>
            <?php endif; ?>



        </td>
    </tr>
</table>


