<style>
	.modal-popup .modal-inner-wrap{
		width:80%;
		margin:2rem auto;
	}
	.a-category-quicview-iframe{width:100%;}
	.sections.nav-sections,
	.page-layout-1column .filter.block,
	.modal-header,.modal-footer,.copyright,.page-title-wrapper{display:none;}
	.modal-popup .modal-content{padding:1rem !important;}
	.product-quickview {
	  overflow: hidden;
	  padding-top: 56.25%;
	  position: relative;
	}
	 
	.product-quickview iframe {
	   border: 0;
	   height: 100%;
	   left: 0;
	   position: absolute;
	   top: 0;
	   width: 100%;
	}
	.category-image img{margin:auto;}
</style>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
$subcats = $category->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<ul style="padding: 0px;float: left;width: 100%">
	<?php
	$_four_count = 0;
	foreach ($subcats as $subcat) {
		if ($subcat->getIsActive()) {
			$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
			$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
			$subcaturl = $subcat->getUrl();
			$_imgHtml = '';
			if ($_imgUrl = $_category->getImageUrl()) {
				$_four_count = $_four_count +1;
				$_show_count = array();
				$_imgHtml = '<img style="width: 100%;" src="' . $_imgUrl . '" />';
				$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
				$_all_data = $_category->getProductCollection()->addAttributeToSelect('*');
				foreach($_all_data as $_a_show){
					$_show_count[]= $_a_show->getIdentifier();
				}
				/* @escapeNotVerified */
				echo '<li style="list-style-type: none;width:24%;margin-right:1%;float:left;text-align:center;"><a href="' . $subcaturl . '
				" class="block-promo" title="' . $subcat->getName() . '">'.$subcat->getName().'<br/>' .$_imgHtml.'<br/>'. count($subcat->getProductCollection()->addAttributeToSelect('entity_id'))  . ' recordings from '. count(array_unique($_show_count)).' shows
				</a></li>';
				if($_four_count == 4){
					echo '<li style="clear:both;"></li>';
					$_four_count = 0;
				}
			}
		}
	} ?>
</ul>

   