<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>






<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
$subcats = $category->getParentCategory()->getChildrenCategories();
?>
<div class="category-view category-view-on"><div class="category-image"><a href="<?php echo $category->getParentCategory()->getUrl();?>"><?php echo '<img src="'.$category->getParentCategory()->getImageUrl(). '" />';?></a></div></div>
<!--ul style="padding: 0px;float: left;width: 100%"-->
	<?php /*
	$_four_count = 0;
	foreach ($subcats as $subcat) {
		if ($subcat->getIsActive()) {
			$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
			$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
			$subcaturl = $subcat->getUrl();
			$_imgHtml = '';
			if ($_imgUrl = $_category->getImageUrl()) {
				$_four_count = $_four_count +1;
				$_show_count = array();
				$_imgHtml = '<img style="width: 100%;" src="' . $_imgUrl . '" />';
				$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
				$_all_data = $_category->getProductCollection()->addAttributeToSelect('*');
				foreach($_all_data as $_a_show){
					$_show_count[]= $_a_show->getIdentifier();
				}
	 * */
				/* @escapeNotVerified */
				/*echo '<li style="list-style-type: none;width:24%;margin-right:1%;float:left;text-align:center;"><a href="' . $subcaturl . '
				" class="block-promo" title="' . $subcat->getName() . '">'.$subcat->getName().'<br/>' .$_imgHtml.'<br/>'. count($subcat->getProductCollection()->addAttributeToSelect('entity_id'))  . ' recordings from '. count(array_unique($_show_count)).' shows
				</a></li>';
				if($_four_count == 4){
					echo '<li style="clear:both;"></li>';
					$_four_count = 0;
				}
			}
		}
	} */ ?>
<!--/ul-->

<style>
	.modal-popup .modal-inner-wrap{
		width:80%;
		margin:2rem auto;
	}
	.a-category-quicview-iframe{width:100%;}
	.sections.nav-sections,
	.page-layout-1column .filter.block,
	.modal-header,.modal-footer,.copyright,.page-title-wrapper,.category-view{display:none;}
	.category-view-on{display:block !important;}
	.modal-popup .modal-content{padding:1rem !important;}
	.product-quickview {
	  overflow: hidden;
	  padding-top: 56.25%;
	  position: relative;
	}
	 
	.product-quickview iframe {
	   border: 0;
	   height: 100%;
	   left: 0;
	   position: absolute;
	   top: 0;
	   width: 100%;
	}
	.category-image{text-align:center;}
</style>






<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>    
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <style>    	
		.plp-list-wrapper {
		  display: grid;
		  grid-template-columns: 20% 12% 12% 20% 12% 12% 12%;
		  grid-gap: 10px;
		  border-bottom:1px solid #999;
		}
		.plp-list-box {
		  padding: 1%;
		}
		.plp-list-box-drop1-1{
        	grid-column: 1 ;
        	grid-row: 1/3;
		}
		.plp-list-box-drop1-2{
        	grid-column: 2 ;
        	grid-row: 1/3;
		}
		.plp-list-box-run3{
        	grid-column: 3/8;
        	grid-row: 2;
        	font-size: 89%;
		}
    </style>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">

            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php 
            $_fix_me_artist = 1;
            $_artist_holder = '';
			$on_artist = '';
            $_fix_me_album = 1;
            $_album_holder = '';
			$on_album = '';
			$_fix_me_track = 1;
			$_track_holder = '';
			$on_track = '';
            foreach ($_productCollection as $_product):
			$on_artist = $_product->getAttributeText('artist');
			$on_album = substr($_product->getAttributeText('track'), stripos($_product->getAttributeText('track'),'_')+1);			
			$on_album = substr($on_album, 0, strrpos($on_album,'_'));
            $on_track = substr($_product->getAttributeText('track'), strrpos($_product->getAttributeText('track'),'_')+1);
			if ($on_artist == $_artist_holder){
            	?>
            	
            	<?php
            }elseif (($on_artist != $_artist_holder) && ($_fix_me_artist == 1)){
            	?>
				  	<h2><?php echo $on_artist;?></h2>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				<?php
							$_artist_holder = $on_artist;			
							$_fix_me_artist = 0;	
			}else{
				$_fix_me_artist = 0;	
				$_artist_holder = $on_artist;										
				?>
					</div>
					<h2><?php echo $on_album;?></h2>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				        <h2></h2>
				<?php
			}
			
			
            if ($on_album == $_album_holder){
            	?>
            	
            	<?php
            }elseif (($on_album != $_album_holder) && ($_fix_me_album == 1)){
            	?>
				  	<h3 style="padding-left:5%;"><?php echo $on_album;?></h3>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				<?php
							$_album_holder = $on_album;			
							$_fix_me_album = 0;	
			}else{
				$_fix_me_album = 0;	
				$_album_holder = $on_album;										
				?>
					</div>
					<h3 style="padding-left:5%;"><?php echo $on_album;?></h3>
				  	<div id="accordion-<?php echo preg_replace('/\W+/', '-', strtolower($on_album)); ?>" data-mage-init='{
				        "accordion":{
				            "active": "",
				            "collapsible": true,
				            "openedState": "active",
				            "multipleCollapsible": true
				        }}'>
				        <h2></h2>
				<?php
			}
			
            
            
            if ($on_track == $_track_holder){
            	?>
            	
            	<?php
            }elseif (($on_track != $_track_holder) && ($_fix_me_track == 1)){ ?>
					<div data-role="collapsible" style="padding-left:10%;">
				        <div data-role="trigger">
				            <span>Track #<?php echo $on_track;?> - <?php echo $_product->getTitle();?></span>
				        </div>
				    </div>
				    <div data-role="content" style="padding-left:15%;">
						<ol>            
				            <li class="plp-list-wrapper">		            			            		            	
				            	<div class="plp-list-box"><strong></strong></div>
				            	<div class="plp-list-box"><strong>Length</strong></div>
				            	<div class="plp-list-box"><strong>Year</strong></div>
				            	<div class="plp-list-box"><strong>Venue</strong></div>		            	
				            	<div class="plp-list-box"><strong>Taper</strong></div>
				            	<div class="plp-list-box"><strong>Transferrer</strong></div>
				            	<div class="plp-list-box"><strong>Source</strong></div>
				            </li>	
							<?php
							$_track_holder = $on_track;			
							$_fix_me_track = 0;	
			}else{
				$_fix_me_track = 0;	
            	$_track_holder = $on_track;
				?>
					</ol>
				</div>
				<div data-role="collapsible" style="padding-left:10%;">
				        <div data-role="trigger">
				            <span>Track #<?php echo $on_track;?> - <?php echo $_product->getTitle();?></span>
				        </div>
			    </div>
			    <div data-role="content" style="padding-left:15%;">
					<ol>            
			            <li class="plp-list-wrapper">		            			            		            	
			            	<div class="plp-list-box"><strong></strong></div>
			            	<div class="plp-list-box"><strong>Length</strong></div>
			            	<div class="plp-list-box"><strong>Year</strong></div>
			            	<div class="plp-list-box"><strong>Venue</strong></div>		            	
			            	<div class="plp-list-box"><strong>Taper</strong></div>
			            	<div class="plp-list-box"><strong>Transferrer</strong></div>
			            	<div class="plp-list-box"><strong>Source</strong></div>
			            </li>					            
				<?php
			}
            
            ?>
            <li class="plp-list-wrapper">                
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <!--a class="plp-list-box plp-list-box-drop1-1" href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a-->
					<div class="plp-list-box">
                     <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
	                    <div class="product-item-inner-OFF">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Playlist')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Playlist') ?></span>
                                            </button>
                                        </form>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>                    	
                    </div>                    
                    <div class="plp-list-box"><?php echo gmdate("H:i:s",$_product->getLength()); ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('year') ?></div>    
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('venue') ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('taper') ?></div>
                    <div class="plp-list-box"><?php echo $_product->getAttributeText('transfer') ?></div>
                    <div class="plp-list-box">Archive.org</div>                                        
            </li>
            <?php endforeach; ?>
        </ol>
    	</div>
    	</div>
    </div>
    
   <?= $block->getToolbarHtml() ?>   
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
